### ISSUE TITLE
Get Create Account to send an email

### ISSUE THREAD

**Issue by vwbaker** [cpe308-309/The_Missing_Semi-Colons#121]
In order to confirm that the user is giving a valid email, we will need to be able to send an email before they are allowed to login so that we can confirm that they gave us a real email and aren't trying to pretend they're anyone else.

**Comment by vwbaker** [comment]
I created a gmail account for glowbe: glowbeinternational@gmail.com.  
I set the environment variables for Heroku and the localhost for myself and all of my teammates to have the password.  That way, we don't have to commit the password of our gmail account to the public repo of github for anyone to see.

**Comment by vwbaker** [comment]
I figured out how to send emails from my Java server using javax.mail dependency.  I can now access our gmail account and send an email to the email provided by the user.  It sends a link to the user that will allow them to confirm that their email using a randomly generated token. The token is saved with the user in the database so that we can look them up by that token later when they confirm their account through the link in their email. This long token makes sure that the user doesn't confirm their account without actually having access to the email they provided.

**Comment by gsocher** [comment]
great explanations in the issue!
