### ISSUE TITLE
Final presentation

### ISSUE THREAD

**Issue by paihsu** [cpe308-309/The_Missing_Semi-Colons#41]
I will make a Google Doc for thr final presentation!

**Comment by amylewis1034** [comment]
Why Michael?

**Comment by paihsu** [comment]
Sorry !!!

**Comment by paihsu** [comment]
The sharing email has been sent, please let me know if you don't get it!

**Comment by paihsu** [comment]
The sides of 
8. Key technology learnings
9. Key learnings in working as a team
10.Key learnings in 308
is done
Hope all of you can check it, and give me feedback on issue!
thank you all!
